version: "3.7"
services:
  backend:
    build:
      context: backend
      dockerfile: .docker/Dockerfile
    environment:
      - PORT=3030
    ports:
      - "3030:3030"
    volumes:
      - ./backend/:/game

  frontend:
    build:
      context: frontend
    environment:
      - PORT=3040
    ports:
      - "3040:3040"
    volumes:
      - ./frontend:/frontend
