name: Test

on:
  push:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "14"

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          lein: "2.9.3"

      - name: Run Clojure tests
        run: |
          cd backend
          lein with-profile test cloverage --codecov
          bash <(curl -s https://codecov.io/bash)

      - name: Run Eastwood linter
        run: |
          cd backend
          lein with-profile test eastwood

      - name: Run Kibit linter
        run: |
          cd backend
          lein kibit

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Yarn Install
        run: |
          cd frontend
          yarn install

      - name: ESLint and Prettier
        run: |
          cd frontend
          yarn lint
